### ISSUE TITLE
Feedback button: Not seeing an option to upload an image for the buttons

### ISSUE THREAD

**Issue by reginabally** [Automattic/crowdsignal-forms#119]
I'm not seeing an option to be able to upload an image for the buttons in the Feedback Button block even though it says we can do that in p58i-as5-p2.

Suggestion: Add buttons on the block settings to upload images for the Feedback and Submit buttons.

**Comment by digitalwaveride** [comment]
Sorry for the confusion! The image upload was removed, as part of an iteration that came out of some earlier Call for Testing feedback. 

Thanks for raising the issue 👍 !!!
