### ISSUE TITLE
Crowdsignal branding is not seen

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/crowdsignal-forms#122]
![image](https://user-images.githubusercontent.com/18581859/117115842-485d0280-adab-11eb-958c-27e833abb8fb.png)

@nagpai reports:

>I created a feedback button using CS free plan account, still unable to see the CS branding (editor as well as front end) . The block options mention it as an option after upgrade. Can be confusing.

**Comment by digitalwaveride** [comment]
Thanks so much for raising!
This is now fixed with https://code.a8c.com/D61019 .
