### ISSUE TITLE
Follow action bar overlaps with Feedback button on single post page

### ISSUE THREAD

**Issue by krutidugade** [Automattic/crowdsignal-forms#132]
Steps to reproduce:
- Add feedback button block to a post
- Open the single post page

Expected Result:
 The feedback button should appear above the action bar

Actual Result:
The action bar overlaps with feedback block making it difficult to click on feedback button

Screenshot:
<img width="1110" alt="Screenshot 2021-05-05 at 2 17 46 PM" src="https://user-images.githubusercontent.com/33723519/117119789-287c0d80-adb0-11eb-8d4e-3de9ef4efb77.png">

**Comment by digitalwaveride** [comment]
We updated the default placement of the button to the bottom left.
This one will be fixed with the shipment of https://github.com/Automattic/crowdsignal-forms/pull/117

Thanks so much of opening the issue! 🙏
