### ISSUE TITLE
[Poll] Answer button height discrepancy between preview and live site

### ISSUE THREAD

**Issue by zaguiini** [Automattic/crowdsignal-forms#204]
When editing the site, I see minimal height for every answer button. The live version looks fine.

| Editor | Live site |
| ------ | -------- |
|  ![image](https://user-images.githubusercontent.com/26530524/145881349-8f32ee09-052a-4c17-b2b5-eeaa0372b03d.png) | ![image](https://user-images.githubusercontent.com/26530524/145881465-0d18c52e-b2e1-4f2e-a7d1-c8b0eb54dacb.png) |

That is because we have [hardcoded line-height to be zero on this file](https://github.com/Automattic/crowdsignal-forms/blob/dcef11003e156a2d102a5425c5f0f3519af86198/client/components/poll/style.scss#L283). Any special reason for that or is it a bug?

**Comment by zachspears** [comment]
Hey @zaguiini, I am working on triaging this issue and am unable to reproduce it. Can you provide specific instructions to reproduce? Thank you!

**Comment by cuemarie** [comment]
📌 ACTIONS
-
- Closing report due to stale conversation. Feel free to reopen and share any thoughts to the inquiry above. Thanks!
