### ISSUE TITLE
Crowdsignal Forms uncached HTTP requests

### ISSUE THREAD

**Issue by digitalwaveride** [Automattic/crowdsignal-forms#229]
P2 post with context: [Crowdsignal Forms uncached HTTP requests](https://codereviewp2.wordpress.com/2022/06/30/crowdsignal-forms-uncached-http-requests/)

> Crowdsignal blocks seem to be doing one (uncached) request to the same endpoint & with the same API key. This is related to the use of [Crowdsignal_Forms_Block::should_hide_branding](https://href.li/?https://opengrok.a8c.com/source/xref/wpcom/wp-content/mu-plugins/crowdsignal-forms/includes/frontend/class-crowdsignal-forms-block.php?r=49c7fe35#66).
> 
> To reproduce this, one only needs to add the same block multiple times to a post. Then using the debug bar you’ll see the repeated HTTP requests.

**Comment by CGastrell** [comment]
I think we should get this on the Crowdsignal Forms refactor project.

**Comment by CGastrell** [comment]
Drafted a PR to move account info to a store branch, but it still fetches multiple times: https://github.com/Automattic/crowdsignal-forms/pull/234
