### ISSUE TITLE
Feedback Button: Provide an option to make email address mandatory

### ISSUE THREAD

**Issue by bsanevans** [Automattic/crowdsignal-forms#99]
Feature request: I was testing the Feedback Button. As a site owner, I wanted to make the email field mandatory - to prevent people spamming me, or anonymously ranting on my site. But this option does not exist right now.

Suggestion: Add a toggle in the block settings, to change whether the email field is mandatory or not.

**Comment by zdenys** [comment]
I can see that the option to make email field mandatory is now present 🥳  

However, the placeholder text in the email field still appears as "Your email (optional)" on the frontend (not in the Editor).

https://user-images.githubusercontent.com/39308239/135997519-ce65cda6-83d4-4bc4-a04b-df8aab3b29ed.mov

| Editor view  | Frontend |
|-------|------|
| ![image](https://user-images.githubusercontent.com/39308239/135997753-247abf6e-653c-48fd-896e-9827311d1bce.png) | ![image](https://user-images.githubusercontent.com/39308239/135997884-6b7aa6cf-f208-42bf-a14a-93835878ce4e.png) |

**What I expect to happen is:**

- [ ] "Your email (optional)" both on frontend and backend only if `Require email address` option is toggled off. 
- [ ] "Your email" both on frontend and backend only if `Require email address` option is toggled off.

**Comment by aicee** [comment]
Also reported in 5477162-zen, they are seeing "(optional)" text in the Email Address field placeholder even if `Require email address` option is enabled.
